# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_wgtBuilding.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wgtBuilding(object):
    def setupUi(self, wgtBuilding):
        wgtBuilding.setObjectName("wgtBuilding")
        wgtBuilding.resize(260, 468)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(wgtBuilding.sizePolicy().hasHeightForWidth())
        wgtBuilding.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(wgtBuilding)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AppTitleWdg = QtWidgets.QWidget(wgtBuilding)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AppTitleWdg.sizePolicy().hasHeightForWidth())
        self.AppTitleWdg.setSizePolicy(sizePolicy)
        self.AppTitleWdg.setMinimumSize(QtCore.QSize(0, 120))
        self.AppTitleWdg.setMaximumSize(QtCore.QSize(16777215, 120))
        self.AppTitleWdg.setStyleSheet("background-color:#ffffff;\n"
"border:0px;")
        self.AppTitleWdg.setObjectName("AppTitleWdg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.AppTitleWdg)
        self.horizontalLayout.setContentsMargins(16, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.AppName = QtWidgets.QLabel(self.AppTitleWdg)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.AppName.setFont(font)
        self.AppName.setObjectName("AppName")
        self.horizontalLayout.addWidget(self.AppName)
        self.verticalLayout.addWidget(self.AppTitleWdg)
        self.line = QtWidgets.QFrame(wgtBuilding)
        self.line.setMinimumSize(QtCore.QSize(0, 2))
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setSizeIncrement(QtCore.QSize(0, 0))
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.bannerBarWdg = QtWidgets.QWidget(wgtBuilding)
        self.bannerBarWdg.setStyleSheet("background-color:#ffffff;\n"
"border:0px;")
        self.bannerBarWdg.setObjectName("bannerBarWdg")
        self.topBannerLayout = QtWidgets.QHBoxLayout(self.bannerBarWdg)
        self.topBannerLayout.setContentsMargins(16, 0, 0, 0)
        self.topBannerLayout.setSpacing(0)
        self.topBannerLayout.setObjectName("topBannerLayout")
        self.BuildingLable = QtWidgets.QLabel(self.bannerBarWdg)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.BuildingLable.setFont(font)
        self.BuildingLable.setObjectName("BuildingLable")
        self.topBannerLayout.addWidget(self.BuildingLable)
        spacerItem = QtWidgets.QSpacerItem(97, 40, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.topBannerLayout.addItem(spacerItem)
        self.toolBtnAdd = QtWidgets.QToolButton(self.bannerBarWdg)
        self.toolBtnAdd.setMinimumSize(QtCore.QSize(40, 40))
        self.toolBtnAdd.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolBtnAdd.setFont(font)
        self.toolBtnAdd.setIconSize(QtCore.QSize(32, 32))
        self.toolBtnAdd.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolBtnAdd.setAutoRaise(True)
        self.toolBtnAdd.setObjectName("toolBtnAdd")
        self.topBannerLayout.addWidget(self.toolBtnAdd)
        self.toolBtnDelete = QtWidgets.QToolButton(self.bannerBarWdg)
        self.toolBtnDelete.setMinimumSize(QtCore.QSize(40, 40))
        self.toolBtnDelete.setMaximumSize(QtCore.QSize(40, 40))
        self.toolBtnDelete.setSizeIncrement(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toolBtnDelete.setFont(font)
        self.toolBtnDelete.setIconSize(QtCore.QSize(32, 32))
        self.toolBtnDelete.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolBtnDelete.setAutoRaise(True)
        self.toolBtnDelete.setObjectName("toolBtnDelete")
        self.topBannerLayout.addWidget(self.toolBtnDelete)
        self.verticalLayout.addWidget(self.bannerBarWdg)
        self.treeWidget = QtWidgets.QTreeWidget(wgtBuilding)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.treeWidget.setFont(font)
        self.treeWidget.setAcceptDrops(True)
        self.treeWidget.setStyleSheet("border:0px;")
        self.treeWidget.setLineWidth(0)
        self.treeWidget.setAutoScroll(True)
        self.treeWidget.setAutoScrollMargin(16)
        self.treeWidget.setIndentation(12)
        self.treeWidget.setUniformRowHeights(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.treeWidget.header().setVisible(False)
        self.verticalLayout.addWidget(self.treeWidget)

        self.retranslateUi(wgtBuilding)
        QtCore.QMetaObject.connectSlotsByName(wgtBuilding)

    def retranslateUi(self, wgtBuilding):
        _translate = QtCore.QCoreApplication.translate
        wgtBuilding.setWindowTitle(_translate("wgtBuilding", "Form"))
        self.AppName.setText(_translate("wgtBuilding", "作业面管理"))
        self.BuildingLable.setText(_translate("wgtBuilding", "单体列表"))
        self.toolBtnAdd.setText(_translate("wgtBuilding", "添加"))
        self.toolBtnDelete.setText(_translate("wgtBuilding", "删除"))
